multiple entities in query_root, list type check
iteria-app/lowcode pull request #130
Opened 2021-06-28 08:31 UTC by rastiQ

Improvements to #124 

- Simplified output, all queries and fragments in one graphql query string
- Checking if query_root is type 'LIST'

2021-06-29 20:54 UTC, rastiQ commented
WIP #111 

Done:

- Query list, by pk
- Optinal arguments
- Building mutation queries

To do:

- returning (mutations)
- mutation type refactoring (I think it is not neccessary to check mutation args to find type)
- more testing

2021-07-01 04:53 UTC, jozef-slezak commented on packages/graphql-lowcode/src/generate/generateGraphqlQueries.ts
> +  const entity = types.find(type => type.name === entityName)
let's create map of types at the beginning of a algorithm

2021-07-01 04:58 UTC, jozef-slezak commented on packages/graphql-lowcode/src/generate/generateGraphqlQueries.ts
> +interface Entity {
Better naming would be `EntityQuery` since there is not only `entityName` and `fields` but also `queryName`

2021-07-01 04:59 UTC, jozef-slezak commented on packages/graphql-lowcode/src/generate/generateGraphqlQueries.ts
> +  [key: string]: any
do not use any type wherever possible

2021-07-01 05:02 UTC, jozef-slezak commented on packages/graphql-lowcode/src/generate/generateGraphqlQueries.ts
> +      if (field.name === 'returning') {
`'returning'` is Hasura specific...
- either: paramterize your generic algorithm with hasura specific logic
- or just try to loop inside

2021-07-12 19:27 UTC, rastiQ commented
WIP #111, #122 
generatePages now generates .graphql files with queries/mutations + fragments from introspection query and replaces useQuery placeholder in template for generated query

2021-07-13 05:34 UTC, jozef-slezak commented on packages/react-lowcode/src/codegen/ast/node.ts
> +    if(node.expression.getFullText().indexOf(name) > 0) {
what is usual value of `node.expression.getFullText()`?
think about `>=` or '=='

2021-07-13 05:35 UTC, jozef-slezak commented on packages/react-lowcode/src/codegen/tests/list/files/page-list-template.txt
> +import useGeneratedQuery from '../generated'
we should generate named imports
test your generated code in demo.iteria.app (use *.txt manully in the vscode web)

2021-07-13 06:52 UTC, mat-app requested changes

2021-07-13 06:52 UTC, mat-app commented on packages/react-lowcode/src/codegen/generation/generators/template/template-resolver.ts
> +                const hookName = `use${generatedQueryName.charAt(0).toUpperCase() + generatedQueryName.slice(1)}s`
Just user here `camalizeString(entity.getName())`

2021-07-13 09:57 UTC, merged